// lib/weather/weatherCodeToLucide.ts
import { WeatherCode, WeatherCondition } from "./types";

export const weatherCodeToLucide: Record<WeatherCode, WeatherCondition> = {
  0: { label: "Clear sky", icon: "Sun" },
  1: { label: "Mainly clear", icon: "Sun" },
  2: { label: "Partly cloudy", icon: "CloudSun" },
  3: { label: "Overcast", icon: "Cloud" },
  45: { label: "Fog", icon: "CloudFog" },
  48: { label: "Depositing rime fog", icon: "CloudFog" },
  51: { label: "Light drizzle", icon: "CloudDrizzle" },
  53: { label: "Drizzle", icon: "CloudDrizzle" },
  55: { label: "Dense drizzle", icon: "CloudDrizzle" },
  56: { label: "Freezing drizzle", icon: "CloudDrizzle" },
  57: { label: "Dense freezing drizzle", icon: "CloudDrizzle" },
  61: { label: "Slight rain", icon: "CloudRain" },
  63: { label: "Rain", icon: "CloudRain" },
  65: { label: "Heavy rain", icon: "CloudRain" },
  66: { label: "Freezing rain", icon: "CloudRain" },
  67: { label: "Heavy freezing rain", icon: "CloudRain" },
  71: { label: "Slight snow", icon: "Snowflake" },
  73: { label: "Snow", icon: "Snowflake" },
  75: { label: "Heavy snow", icon: "Snowflake" },
  77: { label: "Snow grains", icon: "Snowflake" },
  80: { label: "Rain showers", icon: "CloudDrizzle" },
  81: { label: "Heavy rain showers", icon: "CloudRain" },
  82: { label: "Violent rain showers", icon: "CloudRain" },
  85: { label: "Snow showers", icon: "Snowflake" },
  86: { label: "Heavy snow showers", icon: "Snowflake" },
  95: { label: "Thunderstorm", icon: "CloudLightning" },
  96: { label: "Thunderstorm with hail", icon: "CloudLightning" },
  99: { label: "Thunderstorm with heavy hail", icon: "CloudLightning" },
};
